require(jsonlite)
require(tm)
dat <- fromJSON(sprintf("[%s]", paste(readLines('Assignment5/Tweets.json'), collapse=",")))
myCorpus <- Corpus(VectorSource(dat$text))
myCorpus <- tm_map(myCorpus, content_transformer(tolower))
removeURL <- function(x) gsub("http[^[:space:]]*", "", x)
myCorpus <- tm_map(myCorpus, content_transformer(removeURL))
removeNumPunct <- function(x) gsub("[^[:alpha:][:space:]]*", "#", x)
myCorpus <- tm_map(myCorpus, content_transformer(removeNumPunct))
myCorpus <- tm_map(myCorpus, stripWhitespace)
(freq.terms <- findFreqTerms(tdm, lowfreq = 15))
removeHash <- function(x) gsub("#", "", x)
myCorpus <- tm_map(myCorpus, content_transformer(removeHash))
removeArticles <- function(x) gsub("\\sa\\s|\\sat\\s|\\shas\\s|\\she\\s|\\sis\\s|\\sof\\s|\\son\\s|\\sfor\\s|\\sfrom\\s|\\sthe\\s|\\sto\\s|\\swe\\s|\\sin\\s|^rt\\s|\\sthat\\s|\\svia\\s", "", x)
myCorpus <- tm_map(myCorpus, content_transformer(removeArticles))
tdm <- TermDocumentMatrix(myCorpus,control = list(wordLengths = c(1, Inf)))